os: unstable
image: Visual Studio 2017

environment:
  nodejs_version: "Stable"
  matrix:
    # - NODE_ENV: "dev"
    - NODE_ENV: "prod"

platform:
  - x86

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules
  - app\node_modules
  - '%USERPROFILE%\.electron'


shallow_clone: true

clone_depth: 1

install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  # - npm install -g npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - node --version
  - npm --version
  - yarn --version
  - yarn add windows-build-tools --global
  - yarn --ignore-optional
  - yarn

test_script:
  - node --version
  # - yarn run lint
  - yarn run build
  - yarn run test
  # - yarn run test e2e



build_script:
  - node --version
  - set NODE_ENV=production
  - yarn --version
  - yarn run package-win
  - yarn run post-pack

after_build:
  # - ps:
  - FOR /F %%i IN ('dir release /b') DO SET APP_PKG_DIR=%%i
  - ps: $env:PACKAGE_VERSION = node -p -e "require('./app/package.json').version"
  - dir release
  - cd release
  - 7z a peruse-v%PACKAGE_VERSION%-win-x64.zip
  - dir
  - certutil -hashfile peruse-v%PACKAGE_VERSION%-win-x64.zip SHA256 >> %APP_PKG_DIR%.txt
  - echo %PACKAGE_VERSION%
  - echo %APPVEYOR_REPO_TAG_NAME%
  - ps: Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem .\*.txt | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

# artifacts:
#   - path: release/*

deploy:
  release: $(appveyor_repo_tag_name)
  tag: $(appveyor_repo_tag_name)
  description: 'Peruse [Safe] Browser'
  provider: GitHub
  auth_token:
    secure: yYDNGH+3V6HD/LemQHWRMtum9o98noPH8a02NFPJyuVKc+6vQWveTClb3+gRSnuB
 # your encrypted token from GitHub
  # artifact: /.*\.zip/
  draft: true
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag:  true        # deploy on tag push only
