platform:
  - x64

image: Visual Studio 2015
os: unstable
environment:
  nodejs_version: "6.3.1"

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 6.3.1 x64
  - node --version
  - npm --version
  - npm install npm@next -g
  - npm install
  - npm run rebuild:only
  - npm run build


build_script:
  - node --version
  - set NODE_ENV=production
  - npm --version
  - npm run release:windows

 
artifacts: 
    - path: dist/*-win.zip
 
 
after_build:
  - ps: Get-ChildItem .\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - dir dist
  - echo %APPVEYOR_REPO_TAG%
  - echo %APPVEYOR_REPO_TAG_NAME%
before_deploy:
    - dir dist
deploy:
  release: $(appveyor_repo_tag_name)
  tag: $(appveyor_repo_tag_name)
  description: 'Safe Beaker Browser'
  provider: GitHub
  auth_token:
    secure: yYDNGH+3V6HD/LemQHWRMtum9o98noPH8a02NFPJyuVKc+6vQWveTClb3+gRSnuB
 # your encrypted token from GitHub
  artifact: '**/*.zip'
  draft: false
  prerelease: false
  on:
    # branch: release                  # release branch only
    appveyor_repo_tag:  true        # deploy on tag push only
    # appveyor_repo_tag:  true        # deploy on tag push only