name: Unit Tests

on: [push, pull_request]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_ENV: prod
jobs:
  tests:
    name: Test
    runs-on: ${{ matrix.os }}
    if: "!startsWith(github.event.head_commit.message, 'chore(release):')"
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install
        run: yarn install --ignore-engines --network-timeout 800000;

      - name: Lint
        run: yarn lint --quiet
      - name: Peruse Tests
        run: yarn run test-peruse --forceExit
      - name: Extension Tests
        run: yarn run test-exts --forceExit
